# Generated by Django 5.0.3 on 2024-03-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='2023-03-21'),
            preserve_default=False,
        ),
    ]
